name: Machine Learning CI

on:
  push:
    branches: [ main ] # Berjalan otomatis saat melakukan push ke main

jobs:
  train-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install mlflow dagshub pandas scikit-learn matplotlib seaborn

      - name: Run Training
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Menjalankan script
          cd MLProject
          python modelling.py

      - name: Save Artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: model-results
          path: |
            cd MLProject
            confusion_matrix.png
            feature_importance.png
            test_predictions.csv
