name: Machine Learning CI & Docker Build

on:
  push:
    branches: [ main ]

jobs:
  ml_workflow:
    runs-on: ubuntu-latest
    
    env:
      # PENTING: Gunakan nama repo DagsHub yang sesuai dengan URL browser Anda
      MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/Eksperimen_SML_Annisa-Zalfa.mlflow
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install mlflow dagshub pandas scikit-learn matplotlib seaborn docker

      - name: Run MLflow Project (Training)
        id: train_step
        run: |
          # Jalankan training
          mlflow run MLProject --env-manager local --run-name "CI_Workflow_Run"
          
          # Ambil Run ID terbaru menggunakan perintah formal mlflow
          # Ini mencari run terakhir yang sukses di experiment 0
          LATEST_RUN_ID=$(mlflow runs list --experiment-id 0 --max-results 1 | awk 'NR==3 {print $1}')
          
          if [ -z "$LATEST_RUN_ID" ]; then
            echo "Error: Run ID tidak ditemukan!"
            exit 1
          fi
          
          echo "RUN_ID=$LATEST_RUN_ID" >> $GITHUB_ENV
          echo "Berhasil mendapatkan Run ID: $LATEST_RUN_ID"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          echo "Waiting for DagsHub artifact synchronization..."
          sleep 45

          # Sekarang ${{ env.RUN_ID }} sudah pasti terisi
          echo "Building image for Run ID: ${{ env.RUN_ID }}"

          mlflow models build-docker \
            -m "runs:/${{ env.RUN_ID }}/model_classifier_advanced" \
            -n "${{ secrets.DOCKERHUB_USERNAME }}/healthrisk-model:latest" \
            --enable-mlserver
          
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/healthrisk-model:latest

      - name: Save Artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: model-results
          path: |
            MLProject/*.png
            MLProject/*.csv
