- name: Build and Push Docker Image
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/Eksperimen_SML_Annisa-Zalfa.mlflow
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # 1. Ambil Run ID
          NEW_RUN_ID=$(cat MLProject/run_id.txt)
          echo "Building Docker for Run ID: $NEW_RUN_ID"

          # 2. WAJIB: Berikan jeda 30 detik agar DagsHub selesai sinkronisasi artefak
          echo "Waiting for DagsHub to sync artifacts..."
          sleep 30

          # 3. Jalankan build dengan path yang sudah kita lihat di screenshot
          mlflow models build-docker \
            -m "runs:/$NEW_RUN_ID/model_classifier_advanced" \
            -n "${{ secrets.DOCKERHUB_USERNAME }}/healthrisk-model:latest" \
            --enable-mlserver
          
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/healthrisk-model:latest

      - name: Save Artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: model-results
          path: |
            *.png
            *.csv
