name: Machine Learning CI & Docker Build

on:
  push:
    branches: [ main ]

jobs:
  ml_workflow:
    runs-on: ubuntu-latest
    
    env:
      # PENTING: Gunakan nama repo DagsHub yang sesuai dengan URL browser Anda
      MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/Eksperimen_SML_Annisa-Zalfa.mlflow
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install mlflow dagshub pandas scikit-learn matplotlib seaborn docker

      - name: Run MLflow Project
        id: train_step
        run: |
          mlflow run MLProject --env-manager local --run-name "CI_Workflow_Run"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |

          # 1. Jeda waktu 30-45 detik agar DagsHub selesai memproses upload artefak
          echo "Waiting for DagsHub artifact synchronization..."
          sleep 45

          # 2. Build Docker Image (Path model diarahkan ke folder model_classifier_advanced)
          mlflow models build-docker \
            -m "runs:/9c9210cb8827494ca10091211de2f23f/model_classifier_advanced" \
            -n "${{ secrets.DOCKERHUB_USERNAME }}/healthrisk-model:latest" \
            --enable-mlserver
          
          # 3. Push ke Docker Hub
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/healthrisk-model:latest

      - name: Save Artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: model-results
          path: |
            MLProject/*.png
            MLProject/*.csv
