name: Machine Learning CI & Docker Build

on:
  push:
    branches: [ main ]

jobs:
  train-and-save:
    runs-on: ubuntu-latest
    # Pindahkan env ke sini agar berlaku untuk SEMUA steps
    env:
      MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/Eksperimen_SML_Annisa-Zalfa.mlflow
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install mlflow dagshub pandas scikit-learn matplotlib seaborn docker

      - name: Run Training
        run: |
          cd MLProject
          python modelling.py

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        env:
          # Pastikan variabel ini ada di sini agar dikenali oleh MLflow CLI
          MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/Eksperimen_SML_Annisa-Zalfa.mlflow
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Ambil Run ID
          NEW_RUN_ID=$(cat MLProject/run_id.txt)
          echo "Building Docker for Run ID: $NEW_RUN_ID"

          mlflow models build-docker \
            -m "runs:/$NEW_RUN_ID/model_classifier_advanced" \
            -n "${{ secrets.DOCKERHUB_USERNAME }}/healthrisk-model:latest" \
            --enable-mlserver
          
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/healthrisk-model:latest

      - name: Save Artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: model-results
          path: |
            MLProject/*.png
            MLProject/*.csv
